### ISSUE TITLE
IDE font broken in Material Theme Plugin version v2.9.4.1

### ISSUE THREAD

**Issue by pavinthan** [ChrisRM/material-theme-jetbrains#1004]
IDE font broken after update Material Theme Plugin to v2.9.4.1

<img width="381" alt="screen shot 2018-10-18 at 11 32 33 am" src="https://user-images.githubusercontent.com/13897936/47134203-88316c80-d2c9-11e8-9918-2ce4f05f43bb.png">

**Comment by mallowigi** [comment]
What’s broken?

**Comment by crazy-max** [comment]
I have unticked `Material Fonts` option for the moment :

Before :

![image](https://user-images.githubusercontent.com/1951866/47139232-91b3d800-d2bb-11e8-9726-d6947ffb8069.png)

After :

![image](https://user-images.githubusercontent.com/1951866/47139247-9c6e6d00-d2bb-11e8-8d58-2b3aec6e2dbd.png)

**Comment by kstratis** [comment]
Yeap. I second that. However until this gets fixed @crazy-max's workaround works fine.

**Comment by mbogdanos** [comment]
+1 on this. Updated today and was frustrated by this. Please note that the workaround does not work for the tool windows' font for me, only for the rest of the IDE UI components.

**Comment by mallowigi** [comment]
Leaving this open until I'm content with the result but basically, the theme is now bundled with the Material Font, Roboto. It's different from before as before it expected the user to install the font manually, and reverted to using the default font if Roboto wasn't found in the computer.

If you don't want Roboto, you can either uncheck the "Material Fonts" feature or change the font in the Appearance Setting.

**Comment by kstratis** [comment]
@mallowigi Just tested this again in **v2.9.4.2** and it seems the problem is still there...

**Comment by mallowigi** [comment]
Describe the problem, my problem was that antialiasing wasn’t working yesterday, but I think that now it works better.

**Comment by mbogdanos** [comment]
> If you don't want Roboto, you can either uncheck the "Material Fonts" feature or change the font in the Appearance Setting.  

This workaround does not work for the whole UI. Only the IDE menus and toolbars are updated. The tool windows' content still render with the bundled font.
![screenshot_2018-10-19_09-50-02](https://user-images.githubusercontent.com/39557593/47202113-e66f5580-d384-11e8-922b-b8ba828f70bb.png)

**Comment by mallowigi** [comment]
It should change once restarted

**Comment by pavinthan** [comment]
Yah, It's nook nice, Thank you 👍

**Comment by mallowigi** [comment]
It's actually the opposite, in MacOS the Roboto font looks much better than in Windows. Previously I had Roboto installed in my machine and the theme was using that and for years. But now for the sake of testing I removed that font and for some reason I can't install it back, and now the IDE looks... odd. But on Mac it still looks fine,

This is why i'm keeping this issue open until I'm content with the result.

But I won't be going back to the old behavior, this was the intended behavior all along, simply at the time I didn't had enough experience to make it work so I implemented this poor man's solution, but as a result A LOT of people were complaining about their IDE showing weird characters due to a bad implementation of Roboto that was installed alongside the OS, rather than from Google Fonts. Since I had enough of asking people to read the doc to find a workaround, I decided to take another chance of implementing this without requiring people to install something on their computers.

But I am still experiencing with it, somehow the result is not what I expect...

**Comment by mallowigi** [comment]
Though if I can’t make it work I’ll revert my changes at the end of the day

**Comment by mallowigi** [comment]
Alright I think I got what I want, at least in Windows. Besides now I'm bundling a copied version of Roboto so it wouldn't conflict with the Roboto installed in the computer.

Again that was what was intended from the start, it's just that at the time I couldn't find a way to do it. If you want your font back, simply select "Override fonts" or disable the Material Fonts.
