### ISSUE TITLE
incompatible with RubyMine 2018.3 (RM-183.4284.145)

### ISSUE THREAD

**Issue by dmmat** [ChrisRM/material-theme-jetbrains#1054]
![image](https://user-images.githubusercontent.com/7528598/48980696-330d2580-f0d5-11e8-8eb0-716ae320d9a2.png)

**Comment by mallowigi** [comment]
Weird, I just checked and I don't have this warning. What's your system ?

**Comment by dmmat** [comment]
OS: Manjaro 18.0.0 Illyria
Kernel: x86_64 Linux 4.14.81-1-MANJARO
Shell: zsh 5.6.2
DE: GNOME 
WM: GNOME Shell

**Comment by dmmat** [comment]
![image](https://user-images.githubusercontent.com/7528598/48981986-2395d880-f0e5-11e8-8274-c4f4c99ac543.png)

**Comment by dmmat** [comment]
I installed from jetbrains site (not from AUR) and then worked

**Comment by joveice** [comment]
I got the same problem on PyCharm Pro (2018.3). I install my apps from Toolbox.

**Comment by saghm** [comment]
For anyone still having this problem: I discovered through extensive trial and error that with the AUR `rubymine` package, the issue is fixed if the `build.txt` from the source tarball file is added to `/usr/share/rubymine` after installation, or if the `rm "build.txt"` line is removed from the PKGBUILD before building the package. I suspect that this file previously wasn't necessary but now is.

**Comment by saghm** [comment]
Looks like the latest version in the AUR (2018.3-2) now works
