### ISSUE TITLE
Editor tab height cannot go below 32px

### ISSUE THREAD

**Issue by EivV** [ChrisRM/material-theme-jetbrains#1057]
### Summary
The editor tab bar height cannot be reduced below 32px, although the setting allows for it to be set as low as 18px. No visible changes when changing from 32px to lower, but it is possible to increase the height. 

Having no tabs open (as per #1055) and/or restarting the IDE does not help to reduce the number.

### Expected behavior
Reducing tab height below 32px reduces the visible height as well.

### Actual behavior
No reduction below 32px.

### Environment
```
PyCharm 2018.3 (Professional Edition)
Build #PY-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-11-generic

Material Theme UI v3.0.0-pre4
```

**Comment by nazrhyn** [comment]
Interesting. I know the tabs reverted to _much_ higher than my setting had been in the past when I updated to the latest version, but when I reduced it, I didn't check to see if it was actually taking the value I input.

I have confirmed that mine are visually **32px**, but my setting is **18px**.

![image](https://user-images.githubusercontent.com/1672405/49094987-84ccc180-f235-11e8-8e36-c70ba0517a8b.png)

**Comment by mallowigi** [comment]
fixed in next v

**Comment by detwetter** [comment]
This is most definitely not fixed with the latest version .  A Tab Height of 18 no longer matches the Custom Sidebar Height of 18.  It's almost double the height for the Open File Tabs.  This was not the case before, those Heights would match in Size.

As you can see from this screen grab, both the Project Explorer and Tabs are set to 18 and they do not match anymore:
![image](https://user-images.githubusercontent.com/29411391/49162660-54e6f200-f2f9-11e8-87ed-94693a4576d7.png)

This is how it used to look with both set to 18:
![image](https://user-images.githubusercontent.com/29411391/49162887-ddfe2900-f2f9-11e8-9e20-594d9b0475e4.png)

**Comment by mallowigi** [comment]
I'll try reducing the size as much as i can

**Comment by detwetter** [comment]
Thanks, I appreciate your efforts!!

**Comment by detwetter** [comment]
New Version looks great, thanks!!!
