### ISSUE TITLE
Less Frequent Update Channel

### ISSUE THREAD

**Issue by hackel** [ChrisRM/material-theme-jetbrains#1069]
First off, I want to praise the entire team for this and thank them for their hard work, particularly with the upcoming release of version 3.0.  Unfortunately, we all know that IDEA's plugin system and update mechanisms are lacking.  Requiring users to install updates manually, and then to restart the IDE for every update is a real pain.  Because the developers of this theme are so awesome, it's pretty standard to see Material update notifications every day or more.  This can be a slight annoyance to either continually dismiss these notifications or interrupt my work flow with a restart.

So, my request is that a new stable update channel be created, with updates limited to, say, one per week.  Perhaps these would correspond to minor version updates (if you follow semver).  Users could also subscribe to an edge channel for more frequent updates (patch versions) that follows the current release schedule.

I certainly don't want to create more work for developers, so if this could be automated via milestones, version numbers, or another mechanism that would be ideal.  This was already suggested in #897, but this issue has been nagging at me for months so I wanted to chime in myself.  Thanks again for making IDEA look great!

**Comment by mallowigi** [comment]
The reason why there are frequent updates is usually to fix critical bugfixes after a release. I'm already not creating releases with new features every week, as I have most certainly implemented everything that I wanted to implement. Updates will be becoming less frequent (though I wouldn't say once a month, but perhaps once every two weeks or so). However, bug fixes will still be released whenever they are ready, for that I'm not planning to change the development phase.

I already thought of specific channels, however since I'm the only one working here, and I don't have any QA whatsoever, I'm relying on user feedback to open bugs and point out issues. Therefore putting updates on an EAP channel would dramatically reduce the amount of feedback and not contribute to anything, sadly.

So bear with me for the time being, thanks !
