### ISSUE TITLE
Version number should adhere to IntelliJ IDEA guidelines

### ISSUE THREAD

**Issue by pingpongboss** [ChrisRM/material-theme-jetbrains#109]
Android Studio (probably all IntelliJ IDEA) thinks that the plugin can be updated from 0.1.7 to 0.1.61

Obviously, you mean for 0.1.61 to be a "lesser" version number, but it was parsed to be a "greater version number". I filed a bug for IntelliJ at https://intellij-support.jetbrains.com/hc/en-us/requests/77678, but the solution seems to be that the plugin developer (you) should change your version scheme.

**Comment by talios** [comment]
0.1.61 is _definitely higher_ than 0.1.7 in pretty much every versioning scheme under the sun. Unless what you really want is 0.1.6.1...

**Comment by ciscorucinski** [comment]
@pingpongboss The linked page does not exist. 

I am having a related issue with Android Studio in general (not with this plugin), but I think it sounds like the same kind of issue. 

Currently, I have Android Studio 1.5 Preview EAP.0 (build 141.2314126) installed, and it is telling me I have a new version of Android Studio 1.4.1 (build 141.2343393) and to update to this build. However, there is available Android Studio 1.5 Preview 2.0 (build 141.2343905) that I feel like i should be prompted to install instead.

This seems like this issue is related to JetBrain IDE's as a whole (or just Android Studio) right now, and has nothing to do with the versioning of this plugin or the versioning of Android Stuio builds??? What do you think? Is this even related?

**Comment by ciscorucinski** [comment]
weird, actually my settings were reset back to stable updates for some reason. Also, I seen that v0.1.7 was waiting for review via JetBrains....so maybe v0.1.7 was not available at the time? #107
