### ISSUE TITLE
New JSON format for external theming API

### ISSUE THREAD

**Issue by xdrop** [ChrisRM/material-theme-jetbrains#1138]
Hey, I saw that the internal themes are configured with this `json` format which has a lot more options. Is it possible to use that format for external themes as well?

https://github.com/ChrisRM/material-theme-jetbrains/blob/master/src/main/resources/themes/palenight.theme.json

**Comment by mallowigi** [comment]
Hi, I’m still unsure what to do with the theme api. Sure, it would allow you to configure almost everything, which would give you a lot more options, but on the other hand would be much harder to jumpstart. There are like thousand of properties, which a lot are not even used in the IDE, and would require quite some configuration to get everything right (so far I tried to make them but didn’t get as close as the apparence from the Material Theme).

On the other hand the external theme api is much more straightforward, giving only 14 colors to configure to colorize the IDE. 

I’m planning to use both in the future, giving theme editors the ability to override material theme settings. But since the theme api is still not finished, I’d rather focus on other parts of the development.

However you can use the current theme api, so that you won’t need to depend on the material theme plugin at all.

**Comment by mallowigi** [comment]
Oh and by the way, the file you’re talking about is currently not used in the plugin. I’m using a different implementation completely. I was only testing the theme api :)

**Comment by xdrop** [comment]
Ah okay my bad I thought that file was used, and there would be a way to make supply external themes with that json externally as well :) 

No big deal then, I don't really need it right now I was just wondering if it was possible to use it to customize more stuff in the future.
