### ISSUE TITLE
Pencil Icon overlapping with File Icons

### ISSUE THREAD

**Issue by mbashiq** [ChrisRM/material-theme-jetbrains#1150]
### Summary

Tab file icon overlapping with Pencil Icon when editing files

### Expected behavior

Pencil icon when editing shouldn't overlap with the file icon. A way to adjust padding for the tab text would be great

### Actual behavior

The pencil icon overlaps with file icon making it hard to see while working.

### Screenshots
![Screen Shot 2019-03-09 at 10 56 37](https://user-images.githubusercontent.com/10618499/54067532-7f323f00-425a-11e9-876c-2a269552c121.png)

### Environment

![Screen Shot 2019-03-09 at 11 03 18](https://user-images.githubusercontent.com/10618499/54067579-1e573680-425b-11e9-8e23-b4df73b96202.png)
material

**Comment by mallowigi** [comment]
Not a bug, this is because this is a replacement of the asterisk icon, which overlaps the file icon as well. If it bothers you, you can disable the feature by disabling the "Mark modified files with asterisk" in the settings. You can also try to fork the plugin and add more padding if you want, but I am not interested enough to implement it.
