### ISSUE TITLE
Folder Icons in Rider

### ISSUE THREAD

**Issue by mbeckenbach** [ChrisRM/material-theme-jetbrains#1152]
### Summary

In Rider there are no folder icons displayed as in webstorm.

I'm using the latest release version of rider and material theme.
My project contains asp.net and an angular app in a subfolder.

...

### Expected behavior

Screenshot from Webstorm:

![image](https://user-images.githubusercontent.com/6654388/54082737-9b95b080-431a-11e9-8068-ffb3d310512a.png)

...

### Actual behavior

Screenshot from Rider:

![image](https://user-images.githubusercontent.com/6654388/54082739-a9e3cc80-431a-11e9-8cf2-5f62a725826e.png)

...

### Environment

JetBrains Rider 2018.3.4
Build #RD-183.6092.12, built on March 4, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
I just checked and it looks like Rider's implementation of folders is completely different from the other IDEs. For instance there is no way to set a folder as excluded or as a resource root.

It looks like it's using Resharper components and unfortunately I can't seem to find a way to solve this at the moment. 

I'd suggest you to open an issue at Jetbrains Youtrack to ask if they can reuse regular Project View implementation, but for the moment there is no way to do so.

In my side I'll remove this setting and other non applicable settings from Rider so that there will be no confusion.
