### ISSUE TITLE
Theme support added by jetbrains

### ISSUE THREAD

**Issue by Anutha02** [ChrisRM/material-theme-jetbrains#1166]
First, I really love this theme. Keep up the good work. 

Second, I recently read this: https://blog.jetbrains.com/idea/2019/03/brighten-up-your-day-add-color-to-intellij-idea/

and wanted to know what it means for this theme. Does this change make it any easier to maintain this program? Will this theme require major rewrite and can we expect even better integration throughout the IDE. I am curious to know what functionality will we get/lose after this change.

**Comment by mallowigi** [comment]
First of all, don’t worry, this plugin is not going anywhere nor is it going to be deprecated :)

The Theme api provided by jetbrains is actually something that has been here since the beginning, but only recently they wrote the theme editor allowing users to edit themes by providing a json file instead of requiring to write Java code, the same way VSCode and Sublime Text did. So kudos to them for that it’s really helpful!

However the plugin is way beyond what the theme API is proposing. Perhaps they will close the gap little by little but so far the plugin is way more diverse. It provides many features that are not included in any of the IDE abilities (at the moment) such as custom components, accent color and the many settings that are inside, so yeah it’s still a better experience overall ;)

However just like the tool window refactor from 1.3.1 and the icons refactor from 2.9.0, stuff that wasn’t possible previously is now an open question thanks to the theme api: up to now the plugin was “overriding” the darcula/light theme and switching themes was only possible from the plugin settings and actions. Now we can do it via the Look and Feel switcher as well so I need to adapt the code to provide look and feels as well, and somehow connect it to the material theme switcher. I’ve already done that actually and it looks promising, but I’m currently in the middle of another refactor that is more important than this, so that will wait a bit ;)

On a side note, I’ve released a “lite” version of the plugin using Jetbrains API, that is going to be released very soon. Of course it’s not compatible with the “Premium” version of the plugin but at least it will contempt users that found the plugin too heavy. It will contain the plugin’s bundled themes and color schemes without the customization features, which is actually what is 80% of the users are using.

I’m also thinking of making the plugin a “premiumware” while leaving the lite version free, but it’s just an idea for now, we’ll see after the version 4.0

**Comment by Anutha02** [comment]
@mallowigi Thanks for the information. Looking forward to future releases😄😊
