### ISSUE TITLE
Blade filetype icon not showing

### ISSUE THREAD

**Issue by mikemand** [ChrisRM/material-theme-jetbrains#119]
For .blade.php files, only the PHP filetype icon is showing in the sidebar, not the Blade one. All other filetype icons appear to be working.

Current versions:
Build version: PhpStorm 10.0.1 Build #PS-143.382 November 10, 2015
Java version: 1.8.0_40-release-b92x86_64
Operating System: Mac OS X (10.11.1, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

Happened on PhpStorm 10.0.0 as well.

**Comment by peterpan666** [comment]
Yep same issue here! This issue comes from the regexp that @ChrisRM uses [here](https://github.com/ChrisRM/material-theme-jetbrains/blob/v0.1.7/resources/icon_associations.xml#L6).

I don't really know how to handle this problem, can we just swap line 5 and 6 or do we have to think of a better regexp?

That would be nice to correct this :)

**Comment by a1219062954** [comment]
hello，I have same issue on material theme sublime.
at \Sublime Text 3\Packages\Material Theme\prefs\icon_blade.tmPreferences :
 <dict>
    <key>scope</key>
    <string>source.php, embedding.php</string>
    <key>settings</key>
    <dict>
        <key>icon</key>
        <string>file_type_php</string>
    </dict>
</dict>

how can I modification?

**Comment by ChrisRM** [comment]
This package is for the IntelliJ platform, not Sublime Text. You should post an issue at [equinusocio/material-theme](https://github.com/equinusocio/material-theme)
