### ISSUE TITLE
Welcome window

### ISSUE THREAD

**Issue by cybor97** [ChrisRM/material-theme-jetbrains#1223]
### Summary

There's a bug with Welcome window on Windows with switching actions with keyboard or unfocused

### Expected behavior

Normal, as in rest of themes(hover<>normal state)

### Actual behavior

Strange "mixing" of icons/text of previous element

### Steps to reproduce (if needed)

1. Start IDE without opened project
2. Switch actions

![image](https://user-images.githubusercontent.com/9701800/57178499-9451d580-6e79-11e9-81a5-d1f2382471b1.png)
![image](https://user-images.githubusercontent.com/9701800/57178505-c82cfb00-6e79-11e9-81fc-978011edcad1.png)
![image](https://user-images.githubusercontent.com/9701800/57178510-e09d1580-6e79-11e9-9558-d318dca7455b.png)

### Environment

IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme UI v3.9.3

material_theme.xml
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="accentColor" value="00bcd4" />
    <option name="selectedTheme" value="LIGHTER" />
    <option name="userId" value="-6a31ca73:16a7f857713:-8000" />
  </component>
</application>

**Comment by mallowigi** [comment]
This happens because IntelliJ IDEA doesn't expect selection color with opacity, so while regular Swing accepts and render it well, some parts like this one suppose it's a completely opaque value and ignore the opacity, thus ending with a transparent part and an opaque part.

Since the Theme API also doesn't encourage having transparent values, there is nothing I can do, and I don't want to remove the opacity as well, so... bear with it. You can also open an issue in Jetbrains' Youtrack to support opacity.
