### ISSUE TITLE
Popup menu border not visisble again ba

### ISSUE THREAD

**Issue by KiranMohan** [ChrisRM/material-theme-jetbrains#1255]
### Summary
Popup/Context menu not visible against background on dark themes. This happens even in contrast and hight contrast mode.
...

### Expected behavior
Expecting Popup/Context menu to have proper border/background color to standout against the background color in dark themes.
...

### Actual behavior

Popup/Context menu not visible against background on dark themes. This happens even in contrast and hight contrast mode.

![image](https://user-images.githubusercontent.com/2563628/59561018-46172100-9038-11e9-93e1-759887f93c3a.png)

...

### Environment
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-43-Microsoft 
* Material Theme Plugin version v3.10.0
* OS  - both on Windows, and also on WSL setup.

[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3293929/material_theme.zip)

**Comment by mallowigi** [comment]
This is because of one specific setup that you have:
- No opened files
- Nothing typed in the Search Everything

Since the input background and the frame background have the same color, they are blending (even though they should be having a border, but this is nothing the plugin is controlling). If you type anything you should see a difference.
