### ISSUE TITLE
Changing accent color changes code editor theme

### ISSUE THREAD

**Issue by reubenfirmin** [ChrisRM/material-theme-jetbrains#1270]
#492 # Summary

...

### Expected behavior

Changing accent color should change only the accent color.
...

### Actual behavior

Changing accent color actually changes the code editor theme and various other IDE elements.
...

### Steps to reproduce (if needed)

See video here: https://imgur.com/a/XJyKVjX

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-25-generic

**Comment by mallowigi** [comment]
Hmm, yes, actually if you change anything from the settings, it triggers a full re-activate, and therefore causing the current theme to reload alongside the color scheme.

This could be improved but would be a tad difficult, since there is no way to partially apply settings. The only workaround would be to change accents from the tools menu but obviously it only works with the prebundled accent colors.

**Comment by reubenfirmin** [comment]
This was after an IDE version upgrade (and actually a switch from a tar.gz install to a snap install) if that helps. It's annoying behavior because there's no revert, so your carefully configured editor theme is lost. Thankfully I had a backup of my settings.

**Comment by mallowigi** [comment]
No, it only switches the current color scheme, but you can still go back to your configured scheme using the Quick Switch Panel or through the Color Scheme settings.

No need to rewrite anything.

--
Elior
