### ISSUE TITLE
custom theme in IDEA 2019.1

### ISSUE THREAD

**Issue by yxd0018** [ChrisRM/material-theme-jetbrains#1325]
IntelliJ idea 2019.1
1. During configuring theme, I find the custom theme color doesn't sync with the actual them even the RGB code is. 
![custom_theme_colors](https://user-images.githubusercontent.com/1706618/63043908-25821080-be9b-11e9-8c0f-35f0c84176db.png)

2. Sometimes, just clicking apply or ok in the setting doesn't reflect the change in IDE until restart. One example is the "tab height" setting in tab "tabs". 
3. Also, if I load theme in the custome theme tab, even clicking cancel button, the loaded theme is still applied.

**Comment by mallowigi** [comment]
Can you please share more details about your station? Which IDE (the complete version), which OS, which settings do you have?

**Comment by mallowigi** [comment]
1. OK I managed to reproduce the first one, it's happening when pressing apply, as it tries to change the background color of all elements. 

2. The second one should happen instantly, can you share a video when it happens?

3. Could not reproduce as well, loading theme only applies to the custom theme colors.

**Comment by yxd0018** [comment]
2. Have you tried changing tab height? Does display reflect the change right away?
3. Try change to some random custom theme, and display reflects the change. Then load the predefined custom theme, then cancel it. Then restart ide. 
1. In custom theme, why there are 8 char displayed for 6-char rgb code, as shown in the screenshot?

**Comment by mallowigi** [comment]
- You're right about the tabs, it's happening only because of the recent changes in the tabs API. I'll think of a solution
- Wow you're absolutely right o_O I wouldn't have thought in a million years that it would be persisted... Need to fix this asap
- The 8 char refers to color with opacity, because some values can be transparent (for instance, selection color, or button color). However I've noticed certain parts of the ui that would have been broken when given opacity, so I would need to second check that.

**Comment by mallowigi** [comment]
last release should have fixed most of the issues. As for the first one, for now I can't find a solution, but it's no big deal, you could still close and reopen the settings.

**Comment by yxd0018** [comment]
Since I have idea 2019.1.4, I'm kinda stuck with 3.10.0? How can I get fix besides upgrade IDEA?

**Comment by mallowigi** [comment]
There is no way. Sorry

--
Elior
