### ISSUE TITLE
Shitty JSX

### ISSUE THREAD

**Issue by SPAHI4** [ChrisRM/material-theme-jetbrains#136]
![jsx](https://cloud.githubusercontent.com/assets/1670998/11836281/aadc1c32-a3ea-11e5-8b19-c725a8e0f08a.png)

Webstorm 11

**Comment by kevinjbayer** [comment]
Yeah, this is similar to what I was seeing in RubyMine.

**Comment by benjamincanac** [comment]
+1

**Comment by portOdin** [comment]
+1

**Comment by benjamincanac** [comment]
In order to fix this you have to go in Settings > Editor > Colors & Fonts > XML.

After selecting the current scheme : Material Theme - (Default | Darker | Lighter), click on Save as and copy it because of "Read-only scheme, copy to edit".

Afterwards, you have to select "Tag", uncheck "Use inherited attributes" and uncheck "Background".

**Comment by nonameolsson** [comment]
+1

But thanks @benjamincanac , it did solv my problem. Even though this should be default.

**Comment by ChrisRM** [comment]
Should be fixed in the newest build

**Comment by kabirbaidhya** [comment]
+1
