### ISSUE TITLE
[IntelliJ 2019.3.2] Editor scrollbars not using accent color

### ISSUE THREAD

**Issue by lentus** [ChrisRM/material-theme-jetbrains#1510]
### Summary

When using a custom accent color, the editor scrollbars do not use the new accent color, despite the color being set in `Settings > Editor > Color Scheme > General > Editor > Vertical scrollbar`.

### Expected behavior

The vertical editor scrollbar should be colored with the custom accent color as set in `Settings > Editor > Color Scheme > General > Editor > Vertical scrollbar`.

### Actual behavior

The vertical (and horizontal) editor scrollbar is still colored accoring to the default accent color of my material theme (Arc Dark).

![image](https://user-images.githubusercontent.com/11500248/73448277-bde45280-4360-11ea-93ea-04cddb05a77e.png)

### Steps to reproduce

1. Set Arc Dark theme
2. Set a custom accent color
3. Check that `Settings > Editor > Color Scheme > General > Editor > Vertical scrollbar` colors are set to the custom accent color

### Environment

IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 21, 2020
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: FitNesse, Key Promoter X, Lombook Plugin, com.bruce.intellijplugin.generatesetter, com.chrisrm.idea.MaterialThemeUI, com.microsoft.vso.idea, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, org.sonarlint.idea

Material Theme UI version: 4.11.5
material_theme.xml:
```<application>
  <component name="MaterialThemeConfig">
    <option name="compactSidebar" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="pristineConfig" value="false" />
    <option name="statusBarTheme" value="false" />
    <option name="upperCaseButtons" value="false" />
    <option name="useMaterialFont2" value="true" />
    <option name="useMaterialIcons" value="false" />
    <option name="useColoredDirectories" value="false" />
    <option name="useHollowFolders" value="false" />
    <option name="customSidebarHeight" value="23" />
    <option name="settingsSelectedTab" value="4" />
    <option name="tabsHeight" value="28" />
    <option name="accentColor" value="00b712" />
    <option name="selectedTheme" value="ARC_DARK" />
    <option name="userId" value="-19a8f73f:16c8ab7e287:-8000" />
    <option name="version" value="4.11.5" />
  </component>
</application>
```

**Comment by JuanMME** [comment]
It's happening to me as well using the Material Darker theme.

**Comment by mallowigi** [comment]
I'm on 2020 EAP and I can't reproduce.

Can you please check if the issue is gone too ?

**Comment by JuanMME** [comment]
It doesn't work for me still.

![image](https://user-images.githubusercontent.com/26523723/75134541-eac92280-56de-11ea-9702-84fa17ae1370.png)

I'm using Material Darker theme, Webstorm 2019.3.3, Material Theme UI version 4.2

**Comment by JuanMME** [comment]
Tried it on Webstorm 2020 EAP, the issue persists:

![image](https://user-images.githubusercontent.com/26523723/75135610-61b3ea80-56e2-11ea-9e2f-28e5645262b6.png)

It also affects other parts of the theme. My SCSS variables should be white but for some reason they are gray.

![image](https://user-images.githubusercontent.com/26523723/75135617-66789e80-56e2-11ea-838a-d02b58beb24b.png)

**Comment by lentus** [comment]
Tried on IntelliJ EAP (2020.1), issue persists:
![image](https://user-images.githubusercontent.com/11500248/75190573-e1789e00-5750-11ea-8c63-63ca98f2b6d7.png)

<details><summary>IntelliJ version details</summary>
IntelliJ IDEA 2020.1 EAP (Ultimate Edition)

Build #IU-201.5616.10, built on February 19, 2020

IntelliJ IDEA EAP User

Expiration date: March 20, 2020

Runtime version: 11.0.6+8-b722.15 amd64

VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Windows 10 10.0

GC: ParNew, ConcurrentMarkSweep

Memory: 974M

Cores: 4

Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0

Non-Bundled Plugins: Key Promoter X, com.chrisrm.idea.MaterialThemeUI, Lombook Plugin, 
net.seesharpsoft.intellij.plugins.csv, com.bruce.intellijplugin.generatesetter
</details>

**Comment by mallowigi** [comment]
Another suggestion would be for you to completely delete your custom color schemes (the `_@_...icls`) from the configuration directory. I sometimes find myself with themes losing some colors or with colors not resetted after doing "restore".

**Comment by lentus** [comment]
Using Atom One Dark color scheme on Arc Dark theme , deleted my color scheme files, reset to default, and set the vertical scrollbar settings again to something similar to my accent colour. Didn't hlep unfortunately

**Comment by JuanMME** [comment]
I did a clean install of Webstorm 2020 EAP on a different computer and I have the same issue. I had another issue (probably not related and maybe it's a Webstorm bug, but just in case) where changing the accent color of the theme would actually remove the theme itself:

![image](https://user-images.githubusercontent.com/26523723/75460296-95f90680-5981-11ea-8e47-f7f22b4505ea.png)

As you can see, the Material Darker theme is selected (and applied in theory, hence why the Apply button is disabled), but because I changed the accent color the style went away. Changing to a different theme and then selecting Material Darker again fixes it.

**Comment by r4dixx** [comment]
Coming from a fresh install of Android Studio 3.6.1 (IntelliJ Idea 2019.2). I reproduce the issue too. Even after doing what @mallowigi mentioned above (https://github.com/ChrisRM/material-theme-jetbrains/issues/1510#issuecomment-590773691)

**Comment by mallowigi** [comment]
Just checked now and it works as expected in 2020.1

Can you please update and verify?

**Comment by wba0** [comment]
I'm also having this issue FWIW on JetBrains Rider 2020.1.0 Build #RD-201.6668.197. I tried deleting all the *.ics files and other suggestions in this thread to no avail. The scrollbar in the Explorer pane gets set correctly to the custom accent color but the editor panes retain the default Material Dark color.

**Comment by mallowigi** [comment]
Please read the documentation, you’ll find your answers there

**Comment by JuanMME** [comment]
I just downloaded Webstorm 2020.1 on a clean Windows 10 installation, and I keep having the same issue (I did not import anything). Setting a different accent color changes everything except for the editor scrollbar and the tabs accent colors. The tabs color can be fixed by going to the color scheme and changing it manually, but for the scrollbars that doesn't work either.

![2](https://user-images.githubusercontent.com/26523723/82000357-5eccf400-9658-11ea-9c48-5a9b22672a2e.png)
![1](https://user-images.githubusercontent.com/26523723/82000353-5d033080-9658-11ea-82af-96e4cd5028c4.png)
![3](https://user-images.githubusercontent.com/26523723/82000360-612f4e00-9658-11ea-8e4a-b002d4c4b194.png)
![image](https://user-images.githubusercontent.com/26523723/82001021-6097b700-965a-11ea-82d0-455cd77d9a7d.png)

**Comment by JuanMME** [comment]
This is still not working properly. I just tried it on a brand new installation (Windows 10, in case that matters) and the problem is the same for me. When you pick an accent color everything changes except for the editor vertical scrollbar and the tabs underline. You can then go and manually change the tabs underline color (on Editor > Color Scheme > General > Tabs) and it works, but doing the same for the Vertical scrollbar doesn't work.

**Comment by josephzjw** [comment]
I used the method from @JuanMME and the tabs changed color correctly, but vertical scrollbar remains unchanged. Anyway this theme is really nice, thx!

**Comment by Helixar** [comment]
same issue
![screenshot2](https://user-images.githubusercontent.com/39304785/83524822-6f98b900-a4e4-11ea-8a82-6510e39eb97a.png)

**Comment by devx97** [comment]
Same happening to me. Weird thing is that when I change Material Theme scrollbar color is changing, too, but i can't change this manually

**Comment by sajadko** [comment]
Same happening to me. Clion 2020.3
