### ISSUE TITLE
IDEA2020.1 Can't find Icons

### ISSUE THREAD

**Issue by LiJunYi2** [ChrisRM/material-theme-jetbrains#1549]
Icon Settings cannot be found in version 2020.1

It should contain:
* OS (Windows,)
* IntelliJ Product + version (IDEA 2020.1)
* Material Theme Plugin version 5.1.2

**Comment by mallowigi** [comment]
Please read the changelog

**Comment by Yohandah** [comment]
@mallowigi then please update the plugin page that says : 

> Replacement of all icons with colorful Material Design icons

**Comment by mallowigi** [comment]
Replace it by what? It is still available, even if it’s distributed within multiple plugins. Or would you want me to have multiple documentation pages, each for one plugin ?

**Comment by Yohandah** [comment]
I just feel like it needs to be specified more clearly, because reading the plugin page (most users won’t go further), the user expects the icons to change just by downloading the extension that specifies « replace the icons ». 

No need to be so agressive it’s just an advice you’re free to ignore it 😉

**Comment by mallowigi** [comment]
I see, sorry if I sounded a little rude. I know this would become an issue when most people will be updating to the v5, but I don't know how I could have expressed differently. Also, theoretically users should have got a notification in their IDE to inform them of the icons plugin, was it not ?

**Comment by Yohandah** [comment]
Well I missed the notification because I thought it was an ad. 

And when I updated to v5 my theme was disabled (I had material darker but it was switched back to Dracula) and the icons missing so I closed IntelliJ immediately to see if a restart fixed it! 

I think that a single link to the Icon plugin in the Material Theme plugin description should be enough, as well as on the website page in the part that talks about icons

**Comment by mallowigi** [comment]
Well I added a mention of it in the Getting Started Page, in the documentation pages regarding the icons, and I added notifications about it. True, it's not in the README yet, so there's that... 

I'm not very good in marketing (well duh) so yeah sorry for the issue, but this move is fixing a lot of issues.
