### ISSUE TITLE
Custom title bar and project frame don't work well together

### ISSUE THREAD

**Issue by NinoFloris** [ChrisRM/material-theme-jetbrains#1559]
Latest version (5.2.0 in Rider 2020.1 EAP 8 on macos)

<img width="789" alt="Screenshot 2020-04-14 at 18 00 30" src="https://user-images.githubusercontent.com/4218809/79246782-eec12780-7e79-11ea-8418-72fe94c837d7.png">

This is with the custom title bar enabled

**Comment by mallowigi** [comment]
This is an opinion... you can disable it if you don't like it.

**Comment by NinoFloris** [comment]
It's not an opinion, I'd like to use it but only if it can mesh into the custom title bar, isn't that possible? Like this it objectively takes up very valuable vertical space

**Comment by mallowigi** [comment]
The problem with the titlebar is that is should work cross-operating-system, and currently each system has its own title bar implementation. 

At the moment there's no native customization of the title bar. Windows is the easiest since it's enabled by default, but Mac OS requires the "themed title bar" feature to work, and to be honest, it's not a great implementation because of the limitations of the JDK; and Linux has no support at all.

This "Title Bar" extension is a good compromise for now, it's like a Toolbar/NavBar so it's toggleable whenever needed (maybe I'll add to the Toolbars menu as well for easy toggling).

But this feature is open for discussion on the other thread if you want.

**Comment by NinoFloris** [comment]
Did you mean to link to a thread?

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/1556

**Comment by NinoFloris** [comment]
Thanks :)
