### ISSUE TITLE
Feature request: option to disable window title

### ISSUE THREAD

**Issue by dkter** [ChrisRM/material-theme-jetbrains#1628]
With one of the recent updates, the window title is now squeezed next to the menu buttons and it makes the entire thing look cluttered and confusing. I'd appreciate an option to disable the window title altogether, as it doesn't provide any useful information for me anyway.

**Comment by mallowigi** [comment]
What do you mean? Can you provide screenshots?

**Comment by dkter** [comment]
Sure:
![image](https://user-images.githubusercontent.com/34610081/89236888-cd6a7f80-d5bf-11ea-9ab9-e6185356d6d2.png)
![image](https://user-images.githubusercontent.com/34610081/89236908-df4c2280-d5bf-11ea-8efb-488798d77fd4.png)
The highlighted part isn't super helpful, makes the titlebar extremely cluttered, and is easy to confuse for the menu buttons sometimes.
![image](https://user-images.githubusercontent.com/34610081/89237071-3ce06f00-d5c0-11ea-8aa9-df47071c58f0.png)
This is Visual Studio, which does something similar to what I'm talking about and doesn't include the window title at all.

**Comment by mallowigi** [comment]
Umm, I'm not a Windows user but I'm not sure it's coming from the plugin. Have you tried without the plugin ?

**Comment by dkter** [comment]
Yeah, I know it's not coming from the plugin, but I thought it would be nice if the plugin was able to disable it

**Comment by mallowigi** [comment]
No chance :)

1. I'm not a Windows user
2. I'm on hiatus
3. I don't think it's doable since this is something controlled by
JetBrains. But maybe you can open up a feature request in their YouTrack,
you'll never know.

On 4 August 2020 at 16:18:12, David Teresi (notifications@github.com) wrote:

Yeah, I know it's not coming from the plugin, but I thought it would be
nice if the plugin was able to disable it

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisRM/material-theme-jetbrains/issues/1628#issuecomment-668591475>,
or unsubscribe
