### ISSUE TITLE
Allow setting custom colors for Project Frame color

### ISSUE THREAD

**Issue by ffxsam** [ChrisRM/material-theme-jetbrains#1629]
It would be great if we could set our own custom colors for the Project Frame color. (which would be stored in the .idea/ folder)

**Comment by mallowigi** [comment]
I thought about it, actually I am planning to release it as a standalone plugin, but for now I'm truly busy to work on the plugins. So be patient 🗡️

**Comment by michabbb** [comment]
@mallowigi paying customer here: would love to see that, cause usually every project is linked to a specific customer and it would help a lot to see every project in the colors of the customer's CI. since many months went over, i want to remind you, this would be really an extreme nice optical feature that helps to identify the project with the customer. thank you !

**Comment by mallowigi** [comment]
Yep this is in my projects, I'd also want to give the option to replace the title bar color.

I tried to add an icon as well but unfortunately I couldn't do it yet.

**Comment by michabbb** [comment]
thanks for your feedback. an icon might be nice, but choosing the color for the beginning would be nice 😏
