### ISSUE TITLE
[lighter theme] Increase the contrast of tab bar

### ISSUE THREAD

**Issue by kuige** [ChrisRM/material-theme-jetbrains#1683]
Material lighter theme, the text of tab bar is not clear, and it's hard to read, especially the selected tab.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/8212800/105788495-9a77d600-5fbb-11eb-9771-cf34da5cabc4.png">

The contrast is too low.

**Comment by mallowigi** [comment]
You're in Accent Mode

**Comment by kuige** [comment]
It's perfect now when I disable the Accent Mode ! 👍

Is it possible that even in Accent Mode, and the text still clear ? For example, auto adjust the text color when in Accent Mode

**Comment by mallowigi** [comment]
The problem is that the file colors are defined independently of what option you choose. The accent color is suited in general when Accent mode is not enabled. When enabling Accent Mode the setting is entirely different and up to what you want to do.

I'd suggest you read this section: https://www.material-theme.com/docs/configuration/file-status-colors/
