### ISSUE TITLE
Material Theme UI Changing Registry Value ide.mac.transparentTitleBarAppearance

### ISSUE THREAD

**Issue by KapitanKai** [ChrisRM/material-theme-jetbrains#1754]
### Summary
Switching over to Material Theme UI disables registry setting `ide.mac.transparentTitleBarAppearance`. Checking the box to enable this feature and restarting the IDE results in it being disabled again. This only occurs when using Material Theme UI - none of the other UI themes I have change this value, respecting my decision to use transparent title bars.

### Expected behavior
I should be able to turn on this registry setting, that is part of PhpStorm - at least - by default, without Material Theme UI overriding the rule.

### Actual behavior
Material Theme UI overrides the registry setting `ide.mac.transparentTitleBarAppearance` and disables it, if it's enabled.

### Steps to reproduce (if needed)
1. Without Material Theme UI enabled, open registry settings and enable `ide.mac.transparentTitleBarAppearance`.
2. Enable Material Theme UI and restart PhpStorm.
3. `ide.mac.transparentTitleBarAppearance` is disabled.

### Environment
```
PhpStorm 2021.1.1
Build #PS-211.7036.8, built on April 15, 2021
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: org.toml.lang (0.2.146.3826-211), com.chrisrm.idea.MaterialThemeUI (6.4.1), de.espend.idea.laravel (0.15.4), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.209), ru.adelf.idea.dotenv (2021.1), org.rust.lang (0.3.146.3826-211)
```

**Comment by mallowigi** [comment]
The themed title bar setting is not simply a matter of changing something in the registry, but also creates a simili title bar to reproduce the behavior of the title bar, as well as all listeners needed to it. The registry option is needed in order to remove the native title bar, there is no way to work without it.

You can decide to switch the registry value by yourself and live with the original support of the IDE, as experimental as it is. Though you're right pointing out that if you're not a premium user the removal of the registry value should not occur on exit.

**Comment by KapitanKai** [comment]
I understand, thanks for clarifying!
