### ISSUE TITLE
Transform "themed title bar" to "project frame color"

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#1766]

**Comment by dmitry-ivanov** [comment]
IMO, also it would be nice to add an option "Clean title bar" _(I think JetBrains calls it "window header")_.

When enabled - it would make a title bar empty _(instead of `{project} - {file}`)_.

I've written a [proper comment on their tracker](https://youtrack.jetbrains.com/issue/IDEA-255524#focus=Comments-27-4940886.0-0) as a suggestion too, but not sure if _(and when)_ they'd implement it.
