### ISSUE TITLE
Theme is partially reset after restarting machine

### ISSUE THREAD

**Issue by baqirkhan** [ChrisRM/material-theme-jetbrains#1824]
### Summary
Whenever I restart my machine (Windows, Linux or Mac), my theme is reset to this. Then I have to go to material settings and reset the theme again to material darker and only then I can see the expected behavior. Is there something I have configured incorrectly?
...

### Expected behavior
![image](https://user-images.githubusercontent.com/10926994/130902973-5d563364-f2be-4097-b26c-cf54f466721f.png)

...

### Actual behavior
![image](https://user-images.githubusercontent.com/10926994/130902894-4d0d62a3-d98f-4a68-8aa1-840c5c4b15fc.png)
...

### Steps to reproduce (if needed)

1. Restart the machine
2. Open Webstrom

Please note on restarting webstrom this issue does not happen.

You can also add Screenshots for a better understanding.

### Environment
WebStorm 2021.2
Build #WS-212.4746.80, built on July 23, 2021
Licensed to Baqir Khan
Subscription is active until April 15, 2022.
For educational use only.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.tabnine.TabNine (0.4.9), zielu.gittoolbox (212.7.6), com.mallowigi (38.0.0), mobi.hsz.idea.gitignore (4.2.0), name.kropp.intellij.makefile (212.4746.52), quokka.js (1.0.305), ru.adelf.idea.dotenv (2021.3.0.212), ski.chrzanow.foldableprojectview (1.1.1), ImportCost (1.0.7.212), com.chrisrm.idea.MaterialThemeUI (6.8.1.2)

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by baqirkhan** [comment]
Hi,

Yes I m use settings sync. And where can I find `material_theme.xml `?

**Comment by mallowigi** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs
Elior Boukhobza

Programmer, Designer and Food Lover ;)

Mallowigi
***@***.***
https://www.material-theme.com
[image: twitter] <https://twitter.com/Mallowigi>
[image: linkedin] <https://www.linkedin.com/in/eliorboukhobza/>
[image: instagram] <https://www.instagram.com/heliosaian/>
Create Your Own Free Signature
<https://www.hubspot.com/email-signature-generator?utm_source=create-signature>

On 28 August 2021 at 20:25:48, Baqir Khan ***@***.***) wrote:

Hi,

Yes I m use settings sync. And where can I find material_theme.xml ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisRM/material-theme-jetbrains/issues/1824#issuecomment-907658407>,
or unsubscribe

**Comment by baqirkhan** [comment]
There are only .jar files in that directory.
![image](https://user-images.githubusercontent.com/10926994/131283949-5a942352-cb5a-4802-a634-ea244d62f1a9.png)
