### ISSUE TITLE
Color scheme problem

### ISSUE THREAD

**Issue by ahmadov** [ChrisRM/material-theme-jetbrains#226]
I have installed theme successfully but `Material Theme - Default` and `Material Theme - Darker` are not shown in drop down menu. How can I fix it?

**Comment by mjdetullio** [comment]
It's kind of a bug...

In the scheme XML, the version is set to "3" (IntelliJ sometime pre-dating 12.4), the plugin.xml minimum required version is set to 122.519 (IntelliJ 12.2).  The reason they fail to load is because they contain an XML attribute `baseAttributes`, which isn't valid until IntelliJ 14.2.

If you upgrade IntelliJ to at least 14.2 it should work fine.  Ideally the project needs to target a minimum version of 14.2 to take advantage of this.

**Comment by mjdetullio** [comment]
Also, dup of #191
