### ISSUE TITLE
Hard to read file name in tab of a file with uncommited git changes

### ISSUE THREAD

**Issue by mannykary** [ChrisRM/material-theme-jetbrains#229]
See screenshots below. The text is barely readable when the tab is selected.

Selected tab
<img src="http://imgur.com/NBKSOaR.png">

Not selected tab
<img src="http://imgur.com/HyTkE02.png">

**Comment by mannykary** [comment]
I modified the color to #0074a0, which is a slightly lighter shade of blue -- it seems to make the text more readable.

**Comment by mannykary** [comment]
I just realized that this is not valid. I had overridden the default color scheme with a custom one, which had a darker color. Closing this issue.

**Comment by Hazantip** [comment]
how did you fix that? 
<img width="264" alt="screen shot 2017-07-25 at 3 31 34 pm" src="https://user-images.githubusercontent.com/6676603/28572153-702392ea-714e-11e7-975d-e7737e90454e.png">

i almost doesn't see the difference between changed(Credit file)/unchanged fils?

**Comment by mallowigi** [comment]
This is the old behavior, since then Jetbrains changed a few things and now the file colors are inherited from Darcula/Default schemes.

Because of that the plugin cannot provide its own file colors, instead you need to edit the Darcula scheme by yourself and add the file colors you want to.

I wanted to make my own implementation but I am pretty limited compared to the FileColors implementation, so I decided to leave it at that.

**Comment by lxalln** [comment]
@mallowigi I am having this problem today. Could you point me in the right direction for where I can edit that colour.

> …you need to edit the Darcula scheme by yourself and add the file colors you want to.

Using File colors I can change the background of the tab, but I can't find where to change the text colour from the unreadable dark blue.

**Comment by mallowigi** [comment]
Reopening to remind me to order the doc

**Comment by mallowigi** [comment]
https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/file-status-colors/#caveats
