### ISSUE TITLE
can not change text size in appearance

### ISSUE THREAD

**Issue by ljsalm089** [ChrisRM/material-theme-jetbrains#249]
I change the text size in Preferences->Appearance & Behavior->Appearance->UI Options->size to 11, but every time I restart AS, the text in Preferences restore to default size, but in size textview, it still show 11, that trouble me very much.

**Comment by andrzejsliwa** [comment]
+1, I have exactly same problem, font size and type is ignored after installing plugin

**Comment by lidia-freitas** [comment]
+1

**Comment by andrzejsliwa** [comment]
@lidia-freitas I have saved as own theme, I am able to choose custom font, but after restart of intellij this settings are just ignored.

**Comment by ssteinerx** [comment]
If I change the system font, I have to reset the font on every PyCharm restart to get it re-activated.

This is the *only* plugin I've got enabled as I was tracking this down with PyCharm support.

The issue goes away as soon as this theme is uninstalled.

Love it otherwise, but this is really annoying.

**Comment by fresnizky** [comment]
+1

**Comment by kaareloun** [comment]
+1

**Comment by denofevil** [comment]
Duplicates #54

**Comment by rtbins** [comment]
We need to change font options under Editor -> Font.

**Comment by rtbins** [comment]
We need to edit it under Editor -> Color Scheme -> color scheme font.
