### ISSUE TITLE
Highlight color

### ISSUE THREAD

**Issue by StijnVrolijk** [ChrisRM/material-theme-jetbrains#340]
I've noticed since the recent update (0.3), the highlight color changed from a subtle grey (good!) to a bright blue (bad)  as seen below. As you can see the contrast with the icons is also very low. 

This happens both on your theme as the extended Fork so I'm assuming the problem lies either with me or the base theme. I also can't find a specific mention of this in the changelog so I wonder if this is a feature or a bug. 

![image](https://cloud.githubusercontent.com/assets/442529/26627050/62828900-45f9-11e7-8335-f8cbd1ea21d5.png)

Afaik there is no way to set this color from inside PHPStorm itself.

**Comment by mallowigi** [comment]
I see the problem here. Actually, this bright color is the color we have on Windows. However, on Mac this setting was override and replaced with another color, so instead I decided to use the window color.

Actually it's not the right color for lists, it should be the same color as in the menus, so I will do that for next time.

**Comment by StijnVrolijk** [comment]
Okay, thanks for the quick reply!

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.
