### ISSUE TITLE
Light color schemes and block caret

### ISSUE THREAD

**Issue by pix2D** [ChrisRM/material-theme-jetbrains#379]
When the Material plugin is active, and a light color scheme is used (doesn't matter if it's the material one, or another) in combination with a dark block caret then the character within the caret is not readable (presumably it is also black or very dark colored).

With the plugin disabled, dark block carets automatically get white text colors inside them.

**Comment by mallowigi** [comment]
I see, didn't know it would happen. 

I don't see why it sets this black color, but it might be because it thinks that the Look and feel is Darcula (which it is, since the theming is based on this assumption - even if Darcula is not chosen in the list)

Anyway I might fix this in the future but in the meantime I prefered changing the caret color to yellow like other themes instead of the black one. For now it fixes the issue so I will commit this until I have a better solution.

**Comment by pix2D** [comment]
@mallowigi I'm not sure Darcula is the problem. Even if the IDE is set to Darcula, and a light theme is set, the caret text remains white. It's only when the Material Theme plugin is activate that it's black.

Yellow is not really a solution in my eyes, as it's difficult to see on a white background. Thanks for the effort in any case. I can live with toggling the plugin on/off since I only do it twice a day, but if the opportunity arises to fix it properly that would be great.

**Comment by mallowigi** [comment]
The problem is that I don't see how they are setting this black/white color in the code, it looks like they are based on the Look and Feel, so because the Material Themes are based on Darcula, they all inherit from it (even the Lighter theme). It's irrelevant to which Look and feel you selected in the settings.

It's a recurrent issue that I need to look more closely, but atm this is not the priority.

Anyway I would suggest that you set the caret color to something more suited, I'll update the caret color accordingly.
