### ISSUE TITLE
Exact match colors with original theme

### ISSUE THREAD

**Issue by 343434** [ChrisRM/material-theme-jetbrains#386]
Is it possible to have the same colors with the original theme with the same syntax highlighting? Like for javascript the colors are different (1) and for HTML there is no different colors for the ="" (2). I really prefer the original colors. I think it should come by default, is it too much?

1: Original: 
![image](https://user-images.githubusercontent.com/28284108/28116934-d5102b70-673d-11e7-87bf-bac85e7cf57b.png)

    Port (this): 
![image](https://user-images.githubusercontent.com/28284108/28116919-c5cd70d2-673d-11e7-98ea-ae216866b8c1.png)

2: Original: 
![image](https://user-images.githubusercontent.com/28284108/28116885-a0eae9d4-673d-11e7-98c0-f61e728c6e7c.png)

    Port: 
![image](https://user-images.githubusercontent.com/28284108/28116847-7f87f37c-673d-11e7-90a8-8e3540a74fde.png)

**Comment by mallowigi** [comment]
First of all, I must say that having one-one transparency with Sublime Text is impossible. Sublime uses TextMate themes while IDEA uses ICLS.

Second of all, this is what I have 
 
![image](https://user-images.githubusercontent.com/5015756/28121425-c582eb12-6723-11e7-84ec-b7e70df5ce04.png)

So if you have different colors, you probably have an edited version of the scheme, so I would suggest "reset defaults".

Now let's analyze that:

- `$` is blue because it's the colors of functions
- `window` (and `document`) is red because IDEA is loading the "ECMAScript" library and inside, window is an instance of `global`.
- Also, the red is an addition of Chris and is coloring instance fields. I find it better than plain white but it's my humble opinion.
- `fadeOut` is red because when parsing jQuery library, the IDE is interpreting it as a field as well.
- `#header` is blue because of the CSS property "Identifier". It is blue for no reason, but the Sublime theme doesn't specify a color as well. I'm open to suggestions.
- The functions are white because you don't have them in your scope. When you define them, they will turn to blue, the color of functions.

As for the html, there is no way to specify a color for the quotes, so it's a non issue here.


So to conclude:
- You probably have an edited version of the theme. I suggest you update by selecting "Restore defaults"
- I can understand that the red is annoying, but you can easily replace it by white if you want to, but I won't.
- Same for the #header, you can easily specifiy a different color in Colors and Fonts > CSS > Identifier

**Comment by 343434** [comment]
I was using the defaults of PhpStorm and those were the colors of the Javascript file which was different from WebStorm which I just found out, much better in WS, but they are certainly different. And thanks for the analysis, helped me understand the reasons.
