### ISSUE TITLE
More PHP Icons

### ISSUE THREAD

**Issue by bjoernmayer** [ChrisRM/material-theme-jetbrains#391]
Hi,

currently all PHP Files are shown with the elephant icon in project explorer. Problem with that is that you cannot differentiate between Interfaces, Abstract Classes and Classes.

Currently the only solution to that is to deactivate material icons. Which deactivates the nice icons IDE wide.

There are two possible approaches:
- add more PHP icons
- add a new option to deactivate file icons only in project explorer

I would really appreciate such a change :)

**Comment by mallowigi** [comment]
Okay I've analyzed the situation and I have three possibilities:
1. disable php file association altogether, and then the elephant will only show up on PHP files that are not class/interface/abstract/trait (easiest)
2. Implement a FileIconProvider by myself to provide the icons (harder)
3. Personnalize icons for Classes/Interface/Abstract/Trait with the PHP icon (but I need some skills in Design for that)

So I think for now I will go to do the first option, but if someone has design skills I would love to make use of them to create custom Psi Icons instead of the boring C/I circles

**Comment by mallowigi** [comment]
Will be fixed in the next release.
