### ISSUE TITLE
[Suggestion] More discrete JS icon

### ISSUE THREAD

**Issue by iamfreee** [ChrisRM/material-theme-jetbrains#416]
Hi, after the update the js file icon catches too much attention from the eyes.

![image](https://user-images.githubusercontent.com/1500881/29723135-63f674a8-89bb-11e7-97fc-478af126dd1f.png)

A suggestion is to remove the background of the icon and have only the letters JS with the color.

### Environment

WebStorm 2017.2.2
Build #WS-172.3757.55, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
No. If you want this icon yourself you're welcome to fork the project and do your changes in your build.

**Comment by iamfreee** [comment]
Why no discussion on this?

**Comment by mallowigi** [comment]
Because this is an opinionated theme and I cannot take requests for every people not okay with icons or colors.

Plus this was a change in one of the releases, it doesn't make sense to revert back the old icon.

**Comment by ChrisRM** [comment]
Actually, I think this is a relevant discussion. Although this theme and the [original theme](https://github.com/equinusocio/material-theme) by equinusocio is inspired by the [Material Design](http://www.google.com/design/), it should be customized to fit inside an IDE. The icon you are talking about is just an example of that, and I would think that the original author has a good reason for using a different version of the icon, which looks like this: 

![File Type JS](https://github.com/equinusocio/material-theme/raw/develop/icons/file_type_js%402x.png)

When I started with this theme, I first tried with the Material Design icons, but it was too obtrusive. That's why I went for the original theme's icons.

**Comment by mallowigi** [comment]
Welp, if you look at the repository itself you'd see that it uses another icon completely. Anyway after I've looked at the real Atom File Icons (the source of the a-file-icon repository) I've seen that JS icons are the ones I used. And I don't see why it doesn't fit with an IDE.

**Comment by mallowigi** [comment]
Although in all honesty I think the icon is too big and could be reduced a little, but it's not that bad to require working on such a thing.

**Comment by iamfreee** [comment]
Why not use the icon that the original theme uses too?

**Comment by mallowigi** [comment]
A good reason is that most icons are taken from their logos - sass, typescript, html, java... some others don't (xml comes to mind) but usually all icons are taken from their logos. On the other hand, Javascript is one of the few that didn't. Even though Mattia said that he was using a-file-icon icons for his theme he didn't bother change the JS icon, because, well, it is a good icon anyway - not too obtrusive like you said.

However when I first saw the Atom Editor with the Atom File Icons package, I immediately thought that the JS icon is way more suited than the simple JS, so I decided to include it in replacement of the small, JS icon.

But there is one point that I agree of, and it's exactly because I made the icon myself, is that it is a little too big, e.g not enough padding between the lines as in other icons. I will probably take care of it at some point.

But I really want you to get used to it. I know you've been using the old icon for a long time so it's difficult to adapt to changes, but IMO it's more suited to the theme.

**Comment by mallowigi** [comment]
Icon has been resized in v0.10.0, it should be better now

**Comment by iamfreee** [comment]
When the release in the Jetbrains plugin repo will occur? Thanks

**Comment by mallowigi** [comment]
It is currently in beta, I'm waiting on people to open issues, but if not, I will release it next week.

**Comment by sh-a-v** [comment]
@mallowigi  it's no better after update

**Comment by mallowigi** [comment]
It is better, I resized it from 16px to 12px. There is much more padding

**Comment by iamfreee** [comment]
I think its better now.

![image](https://user-images.githubusercontent.com/1500881/30393615-a6b36de4-98b8-11e7-8fc2-53896e75fa4a.png)
