### ISSUE TITLE
Red color choice for class field and static field

### ISSUE THREAD

**Issue by nshusa** [ChrisRM/material-theme-jetbrains#424]
### Summary
Currently, the hex value: FF5370 is used as the default color for class fields and static fields. This is an issue because the hex value is very similar to the color red. Just about EVERY ide out there uses the color red to indicate an error.

### Expected behavior
Any color other than red. Preferably a color that isn't used in Material UI.

### Steps to reproduce (if needed)

1. Install Material UI for IntelliJ
2. Look at any instances (The color is red, this looks like an error)

You can also add Screenshots for a better understanding.

### Screenshot
 ![Image](http://i.imgur.com/HMcPfPM.png)

![Image2](http://i.imgur.com/7MaAsL4.png)

**Comment by mallowigi** [comment]
I'm also thinking about replacing the red color, but for another reason completely: because the theme creator removed this color from static fields and used it in different instances.

I disagree about you about your point though. Errors are a blatant red while this resembles pink red. Besides, all other IDEs usually __underlines__ their errors in red, not the whole field.

And even if it bothers you you can always change it to something else, I won't push this to everyone.
