### ISSUE TITLE
code highlighting error

### ISSUE THREAD

**Issue by Avatarchik** [ChrisRM/material-theme-jetbrains#455]
### Summary

http://take.ms/zWBvK.

### Environment
Rider 2017.2 EAP
Build #RD-172.4144.808, built on September 29, 2017
Rider EAP User
Expiration date: October 29, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
It's not related to the theme nor the color scheme, instead it looks like Rider is marking "hints" with a dotted line in regular themes. However this attribute wasn't themed in Material themes, so it took the default value which is the gray option.

One way to fix it would be to create a dotted line in the schemes instead of the color... wdyt?

**Comment by mallowigi** [comment]
Added in last EAP
