### ISSUE TITLE
Selected File Background & Tool Window Header Colors

### ISSUE THREAD

**Issue by devonzara** [ChrisRM/material-theme-jetbrains#466]
Is it possible to change:

1. The background color of the currently selected file in the Project tree when **not in focus**?
[Image Illustrating Dark Blue Background on Selected File](https://i.imgur.com/ds6gPq9.png)
2. The header background color of a tool window that's currently in focus?
[Image Illustrating Muted Blue Background on Active Tool Window](https://i.imgur.com/jjIwWQM.png)

**Comment by mallowigi** [comment]
If it's possible with the current API? No, clearly not. I tried to hack it once but it gave bad results, and I don't want to hack the UI anymore.

Maybe in a future release, but it is not on the roadmap.

The ideal option of course would be that Jetbrains stopped using hardcoded values. Maybe they will at some point, but for now it is pretty much closed.

**Comment by mallowigi** [comment]
1.  See that ugly hardcoded color
https://github.com/JetBrains/intellij-community/blame/305820e6f5dcce68865da5d2c1e453a8748c4b9b/platform/util/src/com/intellij/util/ui/UIUtil.java#L1227

2. See that ugly hardcoded color
https://github.com/JetBrains/intellij-community/blame/305820e6f5dcce68865da5d2c1e453a8748c4b9b/platform/util/src/com/intellij/util/ui/UIUtil.java#L1847

Until they decide to change this (maybe by creating another Look and feel than Darcula?) we are pretty much stuck since UIUtil is the class you don't want to override!

Maybe open a pull request to extract these values into a static variable if you're patient enough :)

**Comment by devonzara** [comment]
Are a lot of other parts of the UI hard coded like that, or is it just a few places where they seem to have gotten lazy?

I'm not too familiar with the JetBrains way of doing things... what's the difference between issues on that repository and issues in their YouTrack Issue Tracker?

If we could compile a list of UI elements that have things hard-coded that probably shouldn't be, we could organize some sort of effort to get them fixed. Rather it's posting an issue and sharing it for other Material Theme users to up-vote or creating PRs. 

Java isn't my forte, but I'll take a look at that repo when I get a chance.

**Comment by mallowigi** [comment]
They have millions of files, most of I have no clue about, so yeah it could be the case, but usually they do use static variables and here they have gotten lazy (or needed a hotfix or somewhat)

The Youtrack repository is their way of reporting bugs and asking for features. The issues are probably between members of the team or external contributors, but as someone who tried to send a pull request once I got pretty much shunned.

As for the issue at hand, until they are not developing a new Look and Feel, they will probably not fix it since "it works", and no reason to change this for some plugin. At most you can open an issue on Youtrack saying that it would be great for the Material Theme plugin if they could extract these values into static variables that can be overriden, but it would probably fall into oblivion.

**Comment by devonzara** [comment]
Well, a lot of people use this plugin. It's the 19th most downloaded plugin for IntelliJ Community, 27th for Ultimate, 16th for PHPStorm, etc... If I had to guess, I'd say some of their developers use it too... 

That said, I think we could get some traction if we were to compile a comprehensive list of specific items that seem like they should be customizable. Those two things are the only two things that have really stuck out like a sore thumb in my eyes, but I'm sure you probably know of a few more things that you'd have liked to have been able to change and weren't able to.

Once we have a decent list, I'd say making a post on their YouTrack Issue Tracker would be a good start. Furthermore, you could provide a link to it in this repository's readme to encourage those who use the plugin to up-vote it.

**Comment by mallowigi** [comment]
Let's see first if it would be upvoted or just got stuffed into the backlog, then we'll figure out

TBH there are plenty of components that should be themable as easy as the buttons or the checkboxes, but they aren't. On top of my head:
- The Find/Find In Path/Search everywhere search fields. They do not get the material inputs components.
- The tabs height (I did a hack to allow specifying tab height but it wasn't easy, extracting it to a customizable static int would make things much simpler)
- Also I can't change the colors of tab heights other than the editor tabs (ex: debugger)

PS: I'm a little afraid of exposing the plugin to the whole world since I did a lot of "hacking" in it to customize further the UI. I'm not sure it is accepted in the plugins terms of use, and I don't want the plugin being pulled back because of that.
