### ISSUE TITLE
.ignore plugin file colours not working

### ISSUE THREAD

**Issue by Ionaru** [ChrisRM/material-theme-jetbrains#477]
### Summary
Files ignored by the .ignore plugin do not get any special colour.

### Expected behaviour
Files ignored by the .ignore plugin do get a special colour.

### Actual behaviour
![screenshot_20171031_110034](https://user-images.githubusercontent.com/3472373/32218311-c5b6652e-be2a-11e7-98a4-9249abdcd2d0.png)

### Environment
Linux Kubuntu 17.04
IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
Material Theme plugin version 1.0.1
.ignore plugin version 2.2.2

My current settings:
![screenshot_20171031_110312](https://user-images.githubusercontent.com/3472373/32218432-20824c16-be2b-11e7-8cc2-e728fb8e00ec.png)

**Comment by mallowigi** [comment]
Hum, I think I understand what you meant, but it is working, ignored files get the color you put.

However it works only for files, not for directories. For directories, you need to use the settings at `Version Control > File Colors`

**Comment by Ionaru** [comment]
Look at the top screenshot: all `*.db` files should be ignored but they have the same colour as other files.

**Comment by mallowigi** [comment]
@Ionaru have you enabled the setting in the .ignore settings? And had your db files commited into the version control?

Also it looks like I need to save in order to apply the color
![cap](https://user-images.githubusercontent.com/5015756/32406047-8a91fad8-c179-11e7-9a1c-d623037ab59b.gif)

Can I close it now?

**Comment by Ionaru** [comment]
In your video, you turn on ignoring for `.travis.yml`, but it does not change colour.

I have the `ignored file status coloring` option turned on, toggling it seems to have no effect for me. (Both on and off look the same).
My .db files are not commited.

As for a colour: I'd take a slightly darker grey than the regular file colour

**Comment by mallowigi** [comment]
Exactly. If you have already put the file on the source control they will not appear as ignored, because they are not. This is how gitignore works.

I've changed the colour to brown as I have no better option. Setting it darker makes it hard to differentiate between regular files and ignored ones.

If you want to remove the files from the source control, do `git remove *.db --cached`

**Comment by Ionaru** [comment]
Like I said in my previous message: The .db files are not commited (and are not in version control either).

**Comment by mallowigi** [comment]
should work a little better with v1.4.0
