### ISSUE TITLE
Ignore files box is not showing

### ISSUE THREAD

**Issue by sounxrt** [ChrisRM/material-theme-jetbrains#478]
### Summary

When going to Project Structure settings the text box to enter files to ignore/exclude is not showing.

### Expected behavior

A text box to enter manually the files

### Actual behavior

The text box is not showing when material theme is active

![screen shot 2017-11-01 at 11 33 00 am](https://user-images.githubusercontent.com/12937392/32288095-de261182-bf00-11e7-85af-94e2a2b00a28.png)

### Steps to reproduce (if needed)

1. Go to preferences menu
2. Go to Project Structure section

### Environment

```
RubyMine 2017.2.4
Build #RM-172.4155.44, built on September 26, 2017
Licensed to *****
Subscription is active until ****
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1
```

Material Theme settings reseted to default, only the editor font size was changed from 12 to 15 on the color scheme section

**Comment by mallowigi** [comment]
lol, nice find! I didnt know it was there either.

It looks like that because of the larger line height in trees, the directory selector becomes too big for the default Settings Window height, and because when you scroll you are usually inside that directory selector, you can't see the input box.

Just resize the settings window and you'll see it

http://prntscr.com/h64vuc
http://prntscr.com/h64vo4
