### ISSUE TITLE
I can not see the class indicator.

### ISSUE THREAD

**Issue by tonyjs** [ChrisRM/material-theme-jetbrains#53]
I can not see the class indicator and file icon.

I'm using android studio 1.4

I would like to see the indicator on IntelliJ default theme.
ex)
C - class
I - interface

**Comment by ciscorucinski** [comment]
Are you sing a "weird" purple icon instead? The purple icon is suppose to represent a generic Java file I think.

I have a similar persistant (project specific) issue when I open a new project. For example, in one of my projects, none of the java files have their specific icon (class, interface, etc...) but every other icon works. In another project, all of my drawable pictures don't have their new red icon, but every other icon works.

**Comment by ChrisRM** [comment]
I'll create some new icons for the Java files. Coming soon!

**Comment by ciscorucinski** [comment]
Yeah, it took me a while to figure out what the purple icons were. I knew they were Java files, just didn't know what the icon was.

Have you had any issues where the icons are just showing their "generic" icons rather than their specific ones?

Right now, I usually see what I have in the attached picture. Which is wrong. I have seen more specific icons for java files. 
 
![androidstudio_icons](https://cloud.githubusercontent.com/assets/8707125/10479937/21574dc0-72a2-11e5-8dc9-3b3fefe8bc82.PNG)

**Comment by kisstkondoros** [comment]
I have already added some (not so cool) icons, they could be better but better than the standard purple icon...

![image](https://cloud.githubusercontent.com/assets/14231157/10492371/f53130e4-72ab-11e5-8933-a34f0352cefe.png)

**Comment by ChrisRM** [comment]
I'm gonna merge your pull refresh soon @kisskondoros. Just need to finish up some other stuff first. I'll do some improvements icon-wise.

**Comment by kisstkondoros** [comment]
Would be great to see the progress / touched files on a feature branch. :)

**Comment by tonyjs** [comment]
Thanks guys. That's cool @kisstkondoros !

**Comment by ciscorucinski** [comment]
I think if it was closer to the Android Studio look, then it would be really good - dark lettering. Also the color it the green lock is really good;  it is an accent color but it isn't really bright - it is more matte, if you will.

That *type* of coloring should be used for the icons.

**Comment by ChrisRM** [comment]
To be consistent I'll use the colors provided by the original author of Material Theme for sublime. My initial thought is that we need to remove the shadows and be more consistent with the colors, making it fit in with the other icons.

**Comment by ciscorucinski** [comment]
I agree that what every you choose, it must be consistent. I did notice it wasn't consistent with your current icons, but it is a good start. Agree with the removal of the shadows.

I checked @equinusocio's theme in github, and I did find one icon that had lettering inside of it. It does kind of resemblies the look I described above. Muted or matte coloring with dark lettering.

Zoom in and check out the left side >> README.md icon
https://camo.githubusercontent.com/3e08a97d754fc56dc8ea55cab6047e250ad29d38/687474703a2f2f657175696e75736f63696f2e6769746875622e696f2f6d6174657269616c2d7468656d652f6173736574732f696d672f6461726b6572312e706e67

**Comment by ChrisRM** [comment]
Should be fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/46d3a6454a76ccf7d8b0f4dea0eb459630385387

**Comment by ciscorucinski** [comment]
I am a little lost with the release versions you have. I have installed 0.1.5 on my machine. What is the latest you have released. What is the release that this fix will be in?

**Comment by ChrisRM** [comment]
The safest bet would be to use the latest build.

**Comment by ciscorucinski** [comment]
I agree. I want to use the latest. Since this is basically a plugin, I thought it would be automatically updated, but I am not seeing that.

I did some looking and I see the latest build is 0.1.61 via..
https://github.com/ChrisRM/material-theme-jetbrains/commit/436ed08e6a174eca3259936654eaf055bb14d0a6

However, I have seen from...
https://github.com/ChrisRM/material-theme-jetbrains/releases

...that there is no 0.1.6 release tag. The latest release tag is 0.1.5 - which I am on.

Is that why the plugin is not automatically updated? Or is this suppose to be completely manual?

**Comment by ChrisRM** [comment]
This plugin will not update itself before I decide to release it in the Jetbrains plugin repository. I want to sort a couple things out before I do so.
