### ISSUE TITLE
Feature request: material icons in Version Control tool window

### ISSUE THREAD

**Issue by ptrkcsk** [ChrisRM/material-theme-jetbrains#628]
It would be nice if the file tree icons in the Version Control tool window matched the material icons in the Project tool window.

**Comment by mallowigi** [comment]
I also want this feature, but it would collide with the "Material Icons" feature since it applies to the original file icon (as opposed to the file associations which are basically decorators)

When I'll finish this plugin I will update my other plugin, "Atom File Icons" which will do exactly this. You can open an issue there so I would not forget.

**Comment by ptrkcsk** [comment]
[This one?](https://github.com/mallowigi/a-file-icon-idea)

**Comment by mallowigi** [comment]
yes
