### ISSUE TITLE
Can i edit the popup color?

### ISSUE THREAD

**Issue by Darkbish** [ChrisRM/material-theme-jetbrains#668]
I'm using `kotlin` and the popup for parameter info is hard to read.
![parameter popup](https://user-images.githubusercontent.com/8801611/36961628-3f37c8ac-2087-11e8-81d9-67040aa8187f.png)
I want to edit the color, but I can't find the configuration item.

**Comment by mallowigi** [comment]
Have you tried Color Scheme >General > Popups > Tooltip ?

**Comment by Darkbish** [comment]
I try to set `#FFFFFF` for the Tooltip color, but does'nt work.

![_001](https://user-images.githubusercontent.com/8801611/36974370-68b16ce0-20b1-11e8-94f9-a23e0ddde588.png)
The parameter tooltip does not change.
![_006](https://user-images.githubusercontent.com/8801611/36974845-18ea8082-20b3-11e8-9ee0-73b5823c9225.png)
And this tooltip has changed the background-color to be `#FFFFFF`
![_007](https://user-images.githubusercontent.com/8801611/36974964-8cf95bf6-20b3-11e8-8bd0-c736d6d06730.png)
I checked out almost all config and does not find how to set the color for parameter tooltip.

**Comment by mallowigi** [comment]
It's hardcoded by Jetbrains. I'm leaving it open, maybe they will fix it in the future

**Comment by mallowigi** [comment]
Closing this. The gray comes from https://github.com/JetBrains/kotlin/blob/0647ffca36caf6d1dcada8d0129807814df74967/idea/src/org/jetbrains/kotlin/idea/parameterInfo/KotlinFunctionParameterInfoHandler.kt#L83

I don't want the plugin to depend on the Kotlin plugin, so like similar issues with Android Studio, I won't fix this nor try to ask Kotlin to use named colors instead of hardcoded. You are free to open them a pull request to change that though.
