### ISSUE TITLE
Plug-in in the jetbrains official repository

### ISSUE THREAD

**Issue by youbs** [ChrisRM/material-theme-jetbrains#71]
Hi,

Thanks a lot for this, I love it!

Is it possible to have it in the official plugin repository to benefit of automated updates, or is there something preventing it to be registered yet?

**Comment by ChrisRM** [comment]
I think its a bit too early for that. Need to fix a couple things before I register it.

**Comment by youbs** [comment]
Fair enough,
Hope you reach a stable enough version soon, it's really great.

**Comment by soee** [comment]
+1

**Comment by mikeerickson** [comment]
Hey @ChrisRM 

Have you made any significant changes to the Darker Theme, or is it still in "development"  I have a very clean interface right now after making custom color changes, etc. based on the build from "Monday".

I dont want to break my customization, but I still want to have the latest plugin installed.   Assuming since all my changes are customized to my "copy", thinking installing the updated plugins as they are released wont break what I have.

**Comment by ChrisRM** [comment]
It shouldn't break anything, but make sure you backup your "... copy" file before installing the new build.

**Comment by mikeerickson** [comment]
I just tried it on a test installation (WebStorm) and was able to install and update to latest without breaking anything... So, thats a good thing :-)

**Comment by kentongray** [comment]
Hey just wanted to say THANK YOU FOR THIS! You are doing amazing work :godmode: if you throw a donate link somewhere I'd buy you a 6 pack

**Comment by ChrisRM** [comment]
The plugin is waiting for approval; https://plugins.jetbrains.com/plugin/8006
