### ISSUE TITLE
Barely visible text in Auto Complete dialog

### ISSUE THREAD

**Issue by rishabh876** [ChrisRM/material-theme-jetbrains#711]
The text in auto complete dialog does not have proper contrasting text color. Refer screenshot:

<img width="592" alt="screen shot 2018-04-02 at 5 16 46 pm" src="https://user-images.githubusercontent.com/7318534/38197068-065b91ac-36a4-11e8-80a2-e3236412e6d6.png">

### Steps to reproduce
When trying to access the list of variables/methods in an object. 

### Environment
Mac Os High Sierra 
Android Studio 3.1

**Comment by mallowigi** [comment]
Support for AS 3.1 is deprecated. Please wait for 3.2 or install Canary.

**Comment by mustafaozhan** [comment]
Hello @rishabh876 It seems it is Kotlin class I just want give you a trick, If the object (I do not know complete name bec of screenshoot)

`..ListResponse` is nullable you will get this unreadable suggestions when you click '`.`'

In order to prevent it please put `?.` to get suggestions than you will see that you will get suggestions with different strong colors.
