### ISSUE TITLE
Puppet and Ruby icon issues

### ISSUE THREAD

**Issue by dhollinger** [ChrisRM/material-theme-jetbrains#750]
### Summary
Several Icons are using an icon that either doesn't match file type or doesn't properly represent the filetype.

### Expected behavior
* Puppet icon should be using the newer, official [Puppet Logo](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_puppet.svg)
* Puppet manifests (\*.pp) and Puppet templates (\*.epp) should match the Puppet file type definition and show the Puppet icon
* Gemfile, Gemfile.lock, ERB, Rakefile, and *.rake files should display the Ruby icon.

### Actual behavior
* Puppet manifests and templates are seen as Pascal files and always display the Pascal icon.
* The Puppet icon in the repository uses the old Puppetlabs logo, not the current Puppet logo.
* Gemfile icon matches the bundle icon, though there is no official bundler icon. Ruby icon seems to fit better here.
* Gemfile.lock, ERB, Rakefile, and \*.rake files should use the generic Ruby icon as those file types are also heavily used in general ruby projects, not just Rails.

### Steps to reproduce (if needed)
1. Open any Puppet project to see the Puppet icon issue. 
2. Open any Ruby-based project (including Puppet modules) to see the issues relating to Gemfile\*, ERB, Rakefiles, and \*.rake files.

### Environment

RubyMine 2018.1.1
Build #RM-181.4445.97, built on April 11, 2018
Licensed to David Hollinger
Subscription is active until May 19, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

Using default Material UI Darker Theme

**Comment by mallowigi** [comment]
I agree for Puppet, while I like the icon, it seems like it's the old logo and I need to update it to reflect the new one. Besides all icon themes are using the new logo.
I disagree for Gemfile and Gemfile.lock, I don't want them to be confused with Ruby files. Gemfile used the logo for Bundler and Gemfile.lock is using Rails logo (since it is one of the core files of Rails). As for Rake, since they don't have an official logo, I also used the "Rails" logo, though they are less related to rails, so I guess they should have their own icon. I'm thinking of using Jetbrains' logo of a rake.

**Comment by mallowigi** [comment]
I will definitely replace the puppet and rake icons, and theoretically I need to replace Gemfile.lock with a lock icon but I prefer the rails icon.

As for pp files, I got the definition from atom file icons but if puppet projects are more common than pascal files, it makes sense to use them for puppet instead.

**Comment by dhollinger** [comment]
I have no data on if Puppet is more common than Pascal. I probably should've noted that there are no such things as `*.puppet` files in modern puppet, however, there is a (semi) recent type of file called a "puppet template" that is of extension `*.epp` that also needs the puppet icon
