### ISSUE TITLE
Solartized Light theme has dark background in some areas - v2.3.3

### ISSUE THREAD

**Issue by IceMan81** [ChrisRM/material-theme-jetbrains#792]
### Summary
When using the Solarized Light theme, there are areas of the UI that have dark theme colors. This was fixed in a previous released but broke with fixes made to work with the latest EAP. Screen shot attached

Iknow that the latest release notes has highlighted that there could the other bugs, raising it here so that its known. 
...

### Expected behavior
A clean Solarized theme without any dark theme artifacts. 

...

### Environment
IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.2757.3, built on May 28, 2018
IntelliJ IDEA EAP User
Expiration date: June 27, 2018
JRE: 1.8.0_152-release-1248-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

![image](https://user-images.githubusercontent.com/1093778/40744040-2d37f84c-6408-11e8-8978-fd66133dc5dd.png)

**Comment by mallowigi** [comment]
Yeah this is because of the changes they made to the API. I haven't found a fix for this yet. The problem is because if you see in the Look And Feel list you will currently be on Darcula instead of IntelliJ.

For the time being you can switch to IntelliJ then apply the theme again and it should work. Possibly a restart would be needed.

**Comment by IceMan81** [comment]
That works, thanks!
