### ISSUE TITLE
Plugin resets ide.mac.allowDarkWindowDecorations

### ISSUE THREAD

**Issue by andreas-bergstrom** [ChrisRM/material-theme-jetbrains#794]
### Summary

In the registry, the setting for ide.mac.allowDarkWindowDecorations is reset to false on every startup with this plugin enabled. This setting makes the title bar of every window (main and dialoges) dark instead of the typical Mac gray color.

### Expected behavior

Setting the registry key to true hold persist.

### Actual behavior

The registry key is reset to false on every startup, started directly after installing this plugin.

### Steps to reproduce

(for MacOS only)
1. Open Registry
2. Find ide.mac.allowDarkWindowDecorations
3. Close
4. Restart PyCharm

Screenshot here:
https://imgur.com/a/WTAR3Et

### Environment

PyCharm 2018.1.4 (Professional Edition)
Build #PY-181.5087.37, built on May 24, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

Material Theme UI Version: 2.2.3.1

Using all defaults after installation, no custom Material Theme/Material Custom Theme configuration file.

**Comment by mallowigi** [comment]
Actually it is set to false on every project close, and is set to true whenever the option "Dark Title bar" is checked. So if you'd like to keep the option on, simply activate through the plugin settings.

This is because this feature is set explicitly by the plugin while not being related to the plugin itself, so we need to reset to its default value if the user decides to disable or uninstall the plugin.

**Comment by andreas-bergstrom** [comment]
Ah I didn't know that, thanks for the info!
