### ISSUE TITLE
Explain analytic

### ISSUE THREAD

**Issue by mattLLVW** [ChrisRM/material-theme-jetbrains#803]
In the last version, you added analytic, data collection.
Could you please explain:
* What does it collect?
* Why an IDE theme would need to collect data?
Can you mention it in the doc and readme?

I really like this theme, btw.

**Comment by mallowigi** [comment]
I will add it to the docs in a short while. Basically I’m trying to figure out what features or themes are most used by users, in order to prioritize my development phases, or maybe push tips to users.

For instance the monochrome icons is rarely used, so if that trend continues to be true I’ll scrap the feature and maybe propose it as a separate plugin or something.

And again, it is completely anonymous :)

**Comment by mattLLVW** [comment]
Ok. It would be great if it was an opt-in option.
Do you want another issue for this?

**Comment by mallowigi** [comment]
You mean an opt-out option? The option is opt-in by default, you should have seen a popup on the bottom right asking for your consent. If you clicked "Do not agree" no info would be taken.

If you want to opt-out, you can edit your setting file (material-theme.xml) and set the `allowDataCollection` option to false

**Comment by mattLLVW** [comment]
I didn't know you could opt-out. I saw the changeling, looked for info in doc and readme, and made the post. Great! Now I can upgrade 😁
