### ISSUE TITLE
Add theme specific window headers on MacOS.

### ISSUE THREAD

**Issue by cesards** [ChrisRM/material-theme-jetbrains#825]
June 13th, JetBrains got a new IntelliJ IDEA release (2018.2 EAP build 182.3208.16) in which they added support for "Dark Window Headers on macOS". It would amazing to to be able to fit the window header to the color of the color themes supported by plugin.

**Comment by mallowigi** [comment]
What you don't know is that that feature was available in the plugin for a long time (since version 0.7.0) and I recently removed it because they included it in the IDE

So far I don't think there is a way to change the color of this title bar, but I'll check again, maybe in the registry like I did in windows

**Comment by cesards** [comment]
Nice!!! What class did you add to the plugin to make this happen? Could you link your PR/commit to this issue please? Thank you so much :-D

**Comment by mallowigi** [comment]
It’s in the latest commit on the 182 branch, but I’ll publish as soon as I’m done with the next release
