### ISSUE TITLE
Problem with callbackfont

### ISSUE THREAD

**Issue by mi-autumn** [ChrisRM/material-theme-jetbrains#871]
2018.2 material 2.7
![image](https://user-images.githubusercontent.com/38519056/43442818-b4617362-94d1-11e8-8e0f-45b25641a643.png)
have problem with callbackfont

- When not using the theme,callback font works.

- but it dosent work when using the theme,and make input box display symbols instead of Chinese character.

**Comment by mallowigi** [comment]
It is not related. The fallback font is for the editor only, whereas the font you see in the input boxes are from the plugin. The Material Font, Roboto, is latin characters only, which makes sense since usually you code in English, not in Chinese, but if you absolutely need to search for chinese characters, simply deactivate the Material Fonts option and restart.
