### ISSUE TITLE
Tab shadow is not consistent

### ISSUE THREAD

**Issue by kstratis** [ChrisRM/material-theme-jetbrains#883]
### Summary

Tab shadow feature is not consistent.

### Expected behavior

Tab shadow should always be enabled and be consistent regardless of the editor's content.

### Actual behavior

The shadow under the tabs occasionally flashes. Sometimes it's there but not always. After a while it will completely disappear only to appear a few seconds later.

### Steps to reproduce (if needed)

1. Use Material Oceanic and enable contrast mode
2. Open a couple of editor tabs.
3. Start typing or do whatever and keep an eye on the shadow. You'll notice that it's not consistent and appears to "flash" from time to time.

### Environment

* macOS High Sierra
* RubyMine 2018.2
* Material Theme v2.7.2 (also noticed it in v2.7.1)

**Comment by s-trooper** [comment]
how to disable this feature?

**Comment by mallowigi** [comment]
there is a setting for that

**Comment by Kosyne** [comment]
This was closed awfully fast. Can this be looked at again, or at least can an option to disable the shadow be added? It's annoying enough when using a split editor layout to make me switch back to the default theme :/

**Comment by mallowigi** [comment]
I'll add a registry option for that.

**Comment by mallowigi** [comment]
Ok I've decided to not do that. I don't want to introduce an option for every little tweak as it would overload the settings which are already way overloaded.

It's not that big of a deal IMO but if that really pisses you off, you can still fork the project and remove this tweak.

**Comment by Kosyne** [comment]
To clarify, the tweak in question was requested as a workaround for the original issue.

The original issue at hand is a bug, not an enhancement request. The shadow itself bugs out and flickers with each character typed.

**Comment by mallowigi** [comment]
What is your environment? In Windows and Mac i don't see that flicker.

**Comment by Kosyne** [comment]
Two different windows 10 machines, one up to date, and one not up to date. It happens across PyCharm, Rider, DataGrip, and WebStorm. I use the OneDark theme and the only other plugin I have installed is Code Glance.

Sorry for the lack of detail on the previous responses, I was submitting via phone.

I'll try to get a vid of the behavior happening because it's 100% consistent for me on all the systems I've tried it on so far. I think it may have something to do with code linting perhaps. But as you type in an actual project file (not necessarily a dummy text file), while you're typing the shadow disappears, and when you stop, it reappears. It seems to treat spaces differently.

Here's a clip of it happening: https://i.imgur.com/LSkDWFk.gifv

**Comment by mallowigi** [comment]
Alright will add a new setting for the next version

**Comment by MengJueM** [comment]
thanks for the excellent work. I saw the changelog 2.9.2 that wrote "Add setting for enabling/disabling Tab Shadow", can you show the the path to enabling and disabling under jetbrain's preference? actually I didn't find that after checking the "Material Design" tab.

**Comment by tanhernandez** [comment]
Might be late, but for those who are having troubles finding the option:
Go to Settings > Appearance and Behaviour > Material Theme.

Then in the Advanced Setting section, there is a Components tab under it. Click that.
After clicking the Components tab, the Tabs Shadow checkbox will be revealed.

![tab-shadow](https://user-images.githubusercontent.com/12733140/55139433-b8324500-5170-11e9-8451-69bda8f29ef2.png)
