### ISSUE TITLE
White stripe marks in "Project" sidebar

### ISSUE THREAD

**Issue by roboslone** [ChrisRM/material-theme-jetbrains#894]
### Summary
Project view got white stripe marks (I guess for directories).
Is there a way to turn those off?

<img width="345" alt="screen shot 2018-08-15 at 13 44 57" src="https://user-images.githubusercontent.com/1941275/44144847-cfe827a4-a091-11e8-8d8f-ec5a7cf526c6.png">

### Environment
```
PyCharm 2018.2.2 (Professional Edition)
Build #PY-182.4129.5, built on August 9, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by mallowigi** [comment]
No idea what this is...

**Comment by mallowigi** [comment]
Oh i found it... you can turn it off by disabling the "Bold directories"

Will fix it soon enough

**Comment by roboslone** [comment]
There were no error stripe in "Bookmark" entry.
Disabling "Bold directories" did work, thanks.

**Comment by mallowigi** [comment]
![e](https://user-images.githubusercontent.com/5015756/44267461-f65ca300-a236-11e8-80fb-fdecad07a166.png)

The idea for bold directories was to use the Bookmarks attribute to color them bold (I don't know why I did that) but of course, doing so make them dependant on the bookmarks attribute of the selected color scheme instead of depending on the theme settings.

I need to figure out another solution
