### ISSUE TITLE
change border-line colors in Material DeepOcean theme

### ISSUE THREAD

**Issue by Presto412** [ChrisRM/material-theme-jetbrains#896]
### Summary

The border-lines in Material DeepOcean theme, can be changed to a darker shade, possibly black, making the theme look more elegant. This is a feature request.

### Expected behavior

The border colors are white-ish, that don't really go with the dark scheme(my opinion). Below image is my current setup in VSCode, and you can understand what I'm trying to say..
![image](https://user-images.githubusercontent.com/26374855/44195635-45330b80-a157-11e8-9499-2961aac8d38c.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/26374855/44195563-0735e780-a157-11e8-9452-e17cf5c886d4.png)
The border lines in this are grey to whitish in color, so if that could be changed to black, it would look great.

### Environment

*IDE Information*
CLion 2018.2.1
Build #CL-182.3911.40, built on August 7, 2018
Licensed to Priyansh Jain
Subscription is active until September 22, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29-generic

Material Plugin Version: 2.7.2

**Comment by mallowigi** [comment]
I've fixed that by setting that border color to the same color as the right panel. This is the best i can do.

**Comment by Presto412** [comment]
Awesome! Is the update out?

**Comment by mallowigi** [comment]
Will be available on 2.9

**Comment by proteo** [comment]
Hi, just updated to 2.9-pre and the first thing I noticed is that the border that separates the project view and the editor disappeared. Since the changelog says "Fixed project view border color" I didn't expect this :) Then I stumbled upon this issue, which I guess it may have something to do? Not everybody want their borders invisible I guess.

BTW thanks for your wonderful work on the theme, couldn't live without it!

**Comment by mallowigi** [comment]
Well, I can't please everyone... In my opinion this is how it's supposed to be, just like in Sublime and VSC.

I don't want to introduce more settings everytime I introduce a feature/fix, there is already too much settings and I'm planning to get rid of some.

Jetbrains is creating a way for people to create their own UIs, just like the Material Theme plugin, but without all the tweaks of the MP. I'll make use of this feature to create a "Material Theme Custom" plugin that will allow people to tweak their Material Theme experience in more details, but this is planned for at least 2019.

**Comment by proteo** [comment]
Thanks for your response. It's perfectly fine, I totally understand what you're saying; It's impossible to have a setting for every single UI element and it makes perfect sense to try to match the original theme visuals.

Just one final thought: I'm also a (casual) user of Sublime with the Material theme, and was wondering why the lack of that border feels so natural there, and I think that's because the whole UI is consistent with that model. Sublime (at least when using Material Theme) has no borders at all, and being a simpler UI, that works perfectly. PHPStorm, on the other hand, has lots of widgets, and of course lot of borders. I guess that in the end, what makes this feel somewhat uncomfortable is that affects only one border.
