### ISSUE TITLE
phpstorm unable to install plugin

### ISSUE THREAD

**Issue by samayo** [ChrisRM/material-theme-jetbrains#916]
### Summary

PHPstorm can install any plugin, but this repo has some issues. Personally I am not going to stick around since I have no patience and have chosen another theme, but I hate software that doesn't work, so I wanted to report this so hopefully the next person doesn't pull his hair out like I did

### Expected behavior

donwload the plugin

### Actual behavior

error 404

### Steps to reproduce (if needed)

- Open the Settings/Preferences dialog (OSX/Unix: ⌘,, Windows: Ctrl+Alt+S)
- In the left-hand pane, select Plugins.
- Click Browse repositories... and search for Material Theme UI
- Click Install plugin and confirm your intention to download and install the plugin.

### Environment

Sorry, your environment list will take me half an hour to gather, but I am using phpstorm 9 one windows 10

![capture](https://user-images.githubusercontent.com/5304093/44637782-7e6b4700-a9b3-11e8-9ba9-539c4f0d322d.PNG)

**Comment by mallowigi** [comment]
You know that being unable to download the plugin is not related to the plugin but to the plugin repository right?

You are using a fairly old version of phpstorm, but theoretically you shouldn’t have any problems installing an older version of the plugin compatible with those versions.

Since I have no control about the plugin repository, i suggest you try to download it manually at plugin.jetbrains.com and if that doesn’t work, then it would be an issue with the plugin. Otherwise I suggest you to open an issue to youtrack.jetbrains.com. 

Or you can move along and use your other theme as you said.
