### ISSUE TITLE
Blurry icons when 'file icons' disabled

### ISSUE THREAD

**Issue by sycyhy** [ChrisRM/material-theme-jetbrains#959]
### Summary

Latest version of Intellij (not eap) and latest version of the plugin.

When disabling the 'File icons' in plugin settings it looks like this ->

![icons](https://user-images.githubusercontent.com/5894782/46490860-0d644e00-c801-11e8-807f-676939c8290e.png)

### Expected behavior

All the icons should be reverted to the default ones from Intellij, not blurry custom ones.

**Comment by mallowigi** [comment]
This is an unfortunate issue that I can't solve for the moment as the plugin would not run without it. Maybe I'll be able to find another implementation in the future but at the moment I couldn't find something that works. Basically, even when disabling UI Icons or File icons, some icons need to be replaced, otherwise I'd get a fatal error which was plaguing the 2.9.0 pre

Please bear with it or if you have a solution, I'll gladly take it.
