### ISSUE TITLE
Can't change default font

### ISSUE THREAD

**Issue by mateusdemboski** [ChrisRM/material-theme-jetbrains#99]
Hello, normally i use the @hack font in my editor, but using the theme i can't change the default font.
This is a bug? Why i can't change the default font?

tks,

**Comment by mikeerickson** [comment]
Just just need to save the default theme as a copy (name whatever you want) then you will have full access to change front and any other attribute 

This is not a bug in the plugin, it is the way *Storm works in general.

**Comment by mateusdemboski** [comment]
Tanks for help me @mikeerickson ! =D

**Comment by mikeerickson** [comment]
@mateusdemboski Sure thing, is all good now?  let me know if you have further questions :-)

**Comment by chrissimpkins** [comment]
:+1:  let me know if there is anything you need on our end.

**Comment by mateusdemboski** [comment]
Thanks All, everything is ok now! :+1:

**Comment by ciscorucinski** [comment]
@chrissimpkins I tried Hack with this theme, but the `Equals` sign is being cut off. I only see 1 bar ( - ) instead of the two ( = ). I have tested this with font sizes 10 and 11. If I increase the font size to be 12, then the equal sign looks good, but font size 12 is too big for my preference. 

I assume that is with your project, but I have not tested to see if this is an issue without this theme. @mateusdemboski Are you seeing this issue?

**Comment by chrissimpkins** [comment]
Not an issue that has been reported to us in the past.  Poke me in this discussion if it seems to be something on our end and I would be happy to look into it.

**Comment by ciscorucinski** [comment]
oh wow, I cannot determine who this issue belongs to. However, just switching the color scheme will trigger this issue. So it is not @ChrisRM whole IDE modication; just something with the text editor itself.

1) I used the Default Darcula color scheme with the only modifcation being using Hack size 10.
2) I used the Default color scheme from ChrisRM with the only mod being using Hack size 10.
3) I used my Default color scheme with Hack size 10 (https://github.com/ciscorucinski/ChroMATERIAL)
Notes:

When I switch between (1) and (2) or (1) and (3), the = will display only 1 bar.

@chrissimpkins while changing font sizes (size 7 - 12) using (1) above, I did notice that your = + - are not well-aligned. The only correct, as I feel, alignment is with Hack font size 8. Assuming the = is in the correct alignment, all other sizes have the + and - move up or down. Howeve, I don't know if this has anything to do with this issue.

Also, I noticed that with =, the bottom bar remains in place. It is the top bar that disappears. I assumed before, the whole = symbol was moved down...that was a wrong assumption.

@ChrisRM I don't know what to say. Do you know if anything in the changes you have done could have effected the display of fonts?

**Comment by chrissimpkins** [comment]
Can you confirm the version of the Hack fonts that you are using? 

Here are those glyphs by design:

<img width="734" alt="hack-punctuation" src="https://cloud.githubusercontent.com/assets/4249591/10748712/547b03f4-7c39-11e5-9c04-a8c191ae1651.png">

Perhaps this is a hinting issue?  The Java renderer in the JetBrains editors have provided a source for numerous headaches...

**Comment by chrissimpkins** [comment]
And here is where I am on OS X 10.10.5 + PyCharm 5.0 EAP + JB Material Theme + Hack v2.016:

<img width="327" alt="hack-punc-jb" src="https://cloud.githubusercontent.com/assets/4249591/10748888/ee7b6718-7c3a-11e5-8b23-25b96b2a33fd.png">

**Comment by ciscorucinski** [comment]
OK, I was playing around within Settings >> Editor >> Colors & Fonts, and noticed that given (2) and (3) above, the preview display will display the = with only 1 bar in Java, C/C++, and Groovy. Places in XML, HTML, and properties show = correctly.

Second, with your last question. I am still on 2.012, which is 3 changes behind current. However, that is what I am seeing for Hack font size 8. With the other fonts sizes, I am seeing the horizontal bars of the  + and - line up with either the top or botton = bar. 

Example. 
Size 7: + lines up with bottom = bar. - lines up with the top = bar
Size 9: + lines up with top = bar. - lines up in the center
size 10: + lines up wiht the bottom bar. - lines up in the center4

I am on Win10. Android Studio 1.5 Preview + JB Material Theme + Hack v2.012

**Comment by chrissimpkins** [comment]
Definitely update to the current release version of Hack (v2.015).  We addressed several JetBrains editor / Java renderer associated issues in more recent releases and it is likely that this is the problem here.

Link: https://github.com/chrissimpkins/Hack/releases/download/v2.015/Hack-v2_015-ttf.zip

**Comment by ciscorucinski** [comment]
OK, I just updated, and this is still an issue. I am on v2.015.

I also restarted the IDE to clear any cache

**Comment by ciscorucinski** [comment]
Do you feel like this is an issue with Hack? We can move it to your Issue page

**Comment by chrissimpkins** [comment]
@ChrisRM Chris, do you see any theme related issue in the reports added by @ciscorucinski since this issue was closed?  I am happy to continue this discussion over on our repository and address any typeface vs renderer issues that may be leading to the problem.  It's unclear to me what is causing this.
